### PR TITLE
Refactors installer to be more forgiving of failures

### PR DESCRIPTION
**Pull request by jiblits**
Includes the following:
- List of pre-build dependencies that can be installed with system package manager
  - At the moment this only works for debian-like systems
- Moves perl dependencies into a perldeps file to reduce code duplication
- Moves perl DB package into a conditional clause based on user needs
- Adds 'installed' after successful compilation/installation of each dependency
  - This allows the program to re-execute upon failure and resume where it failed
- Allows administrator to leverage multi-processor systems to speed up dependency compilation

---
This patch makes it easier to deploy LRSDAY in a more disposable fashion (i.e. cloud computing) and such that spinning up a brand new server instance can be done in a very hands off manner.

This doesn't resolve the steps required to setup RepeatMasker, however it's possible to work on automating that installation in a separate patch.

Leverages the following environment variables:

- `MAKE_JOBS=<NUM JOBS>`: Default 2, however can be set to whatever the administrator would like. Speeds up build times. *Note*: There were issues running make with multiple jobs on HAL. Running `make` without any additional jobs resulted in successful builds.
- `INSTALL_DEPS`: Setting this variable causes the script to execute `apt-get install` on the packages listed within the `debiandeps` file. User requires sudo privileges. *Note*: I find that leveraging `tmux` is a great way to have a semi-interactive way to monitor script progress without having to use `nohup`.

Example Usage:

`MAKE_JOBS=8 INSTALL_DEPS=1 ./install_dependencies.sh`

This script was developed on fresh Digital Ocean instances running Ubuntu 18.04.

### CODE REVIEW

**Comment by yjx1217** [comment]
Hi Chris,

Many thanks for the improvement! The installation script does look much nicer than before. 
I've tested it on one of our server and the installation finished smoothly. However, I noticed that gnuplot has not been properly installed under the build directory. There is no corresponding gnuplot directory under the build directory although a path for this  was specified in the `env.sh` file after installation. Not sure if it is because there is a gnuplot installed in the system already but for LRSDAY, I would prefer a fresh installation with that specific version number (v4.6.6). The newer version of gnuplot made some changes which will cause incompatibility-related problem with some of my scripts. So could you look into this issue. In the same vein, maybe remove gnuplot from the file `debiandeps` to ensure this strict version control. 

Thanks again!

Best,
Jia-Xing

**Comment by jiblits** [comment]
Ah there was an error in the `if` test for installing gnuplot. I've removed the package dependency from `debiandeps` and fixed the scripts failure to install gnuplot 4.6.6.

I'm validating a fresh installation of the LRSDAYs dependencies as we speak, and things seem to be working properly.

**Comment by yjx1217** [comment]
Thanks Chris! Another thing that I have noticed is with the following construction, all the packages seem will be downloaded twice. Should you remove the `"wget -nv --no-check-certificate $url -O $download_location"` line in `download_and_extract()`? 

```
# Downloading all the dependencies
download () {
  url=$1
  download_location=$2
  echo "Downloading $url to $download_location"
  wget -nv --no-check-certificate $url -O $download_location
}

download_and_extract() {
    url=$1
    download_location=$2
    echo "Downloading $url to $download_location"
    wget -nv --no-check-certificate $url -O $download_location
    download $url $download_location
    if [[ $download_location =~ \.bz2$ ]]; then
        extract_command="tar -xjf"
    elif [[ $download_location =~ \.xz$ || $download_location =~ \.tar$ ]]; then
        extract_command="tar -xf"
    else
        extract_command="tar -zxf"
    fi
    $($extract_command $download_location)
    rm $download_location

}

Thanks in advance!

Best,
Jia-Xing
```

**Comment by jiblits** [comment]
Ah! Thanks, it's been fixed :)

**Comment by yjx1217** [comment]
Great! I will also test the newly committed version on my side.

Best,
Jia-Xing

**Comment by jiblits** [comment]
[GATK needs to be running on JRE 1.8](https://gatkforums.broadinstitute.org/gatk/discussion/10464/invalid-command-line-malformed-walker-argument)

**Comment by yjx1217** [comment]
Hi Chris, 

Yes, JRE 1.8 will be required. Thanks for catching this. 
We should change the `"● Java runtime environment (JRE) v1.8.0 or newer (https://www.java.com)"` to `"● Java runtime environment (JRE) v1.8.0  (https://www.java.com)" `in the file `"prerequisite.txt"`.

Best,
Jia-Xing

**Comment by yjx1217** [comment]
Hi Chris,

I've finished all the test on my side by running through the SK1 example. I am merging your edits into the base branch now.  Thanks again for the contribution! :-)

Best,
Jia-Xing

**Pull request merged**
